language: node_js
node_js:
  - '9.0.0'
dist: trusty

before_script:
  - npm run server &

script:
  - npm run build:travis
  - sleep 30
  - pushd ./dist
  - python -m SimpleHTTPServer 3000 &
  - popd
  - sleep 30
  - npm run test
  - curl http://localhost:3000
  - 'if [ "$TRAVIS_PULL_REQUEST_SLUG" = "" ] || [ "$TRAVIS_PULL_REQUEST_SLUG" = "$TRAVIS_REPO_SLUG" ]; then npm run e2e:local-travis; fi'

addons:
  sauce_connect: true

after_script:
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
  - bash scripts/gitbook.sh
